monitor_project/monitor_app/urls.py
from django.urls import path, re_path, include
from  . import views


app_name = 'serverapp'  ##https://docs.djangoproject.com/en/3.0/intro/tutorial03/#namespacing-url-names
                        
urlpatterns = [ ##path('', views.login_view, name='login_view'),
                # path('', views.all_details, name='all_details'),
                path('', views.base , name='base' ),  ###https://docs.djangoproject.com/en/3.1/topics/http/urls/#passing-extra-options-to-view-functions
                path('company_server/<str:company_name>/', views.company_server, name='server'),
                path('company_servertable/<str:company_name>/', views.company_servertable, name='servertable'),
                # path('update_links/<str:server_name>/', views.test_links, {'number' : 3}, name='test_links'),
                # path('delete_server/<str:server_name>/', views.delete_server,{'number' : 3}, name='delete_server'),
                path('submitform/', views.form_process, name='form_process'),
                path('form_reply/<str:servername>', views.form_reply, name='form_reply'),
                path('form_newserver/', views.server_form, name='server_form'),
                path('form_response/<str:form_data>/<str:report>', views.server_form, name='server_form'),
                path('confirm/<str:name>/<str:action>', views.confirm_request_new, name='confirm_request_new'),
                path('confirm/<str:name>/', views.confirm_request_new, name='confirm_request_new'),

                re_path(r'^showlinks/(?P<company_name>.+)/(?P<server_name>.+)/$', views.list_links, name='links'), #https://docs.djangoproject.com/en/3.0/topics/http/urls/#using-regular-expressions
                re_path(r'^get_linkparams/(?P<company_name>.+)/(?P<server_name>[\w\s]+)/(?P<link_name>.+)/$', views.linkparameters, name='linkparameters'), #https://docs.djangoproject.com/en/3.0/topics/http/urls/#using-regular-expressions
                re_path(r'^base/(?P<server>.+)/(?P<action>.*)/$', views.base, name='base'), #https://docs.djangoproject.com/en/3.0/topics/http/urls/#using-regular-expressions
                # path('get_linkparams/', views.linkparameters, name='linkparameters'), #https://docs.djangoproject.com/en/3.0/topics/http/urls/#using-regular-expressions
]


# urlpatterns_OLD = [ path('', views.serverlist, name='viewname-serverlist'),
#                re_path(r'^company_servertable(?P<number>[0-9]+)/(?P<company_name>.+)/$', views.company_servertablex, name='servertablex'),
#                  re_path(r'^new_entry_form(?P<number>[0-9]+)', views.new_entry_form, name='viewname-new_entry_form'),

# 	            path('testpathfornoreason/', views.serverlist, name='viewname-serverlist'),
# 	            # ex: /polls/5/
#                 path('server/<int:server_id>/', views.server, name='server'),
#                 path('company/<int:company_id>/', views.company, name='company'),
#                 path('links/<int:company_id>/', views.links, name='links'),
#                 path('all/', views.all_details, name='all_details'),
#                 path('company_server/<str:company_name>/', views.company_server, name='server'),
#                 re_path(r'^get_links/(?P<server_name>[\w\s]+)/$', views.links, name='links'),

# ]

monitor_project/monitor_project/urls.py
from django.contrib import admin
from django.urls import path, include
## https://stackoverflow.com/questions/9371378/warning-not-found-favicon-ico
#from django.views.generic import RedirectView
#from django.conf.urls import url
#   url(r'^favicon\.ico$',RedirectView.as_view(url='/static/serverapp/aritari-colorlogo.png')),


urlpatterns = [
    path('', include('monitor_app.urls')),  ## 127.0.0.1:8000/serverapp
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),   ### for authenticating and logging in users.
]

monitor_project/monitor_app/forms.py
from django import forms

## http://www.learningaboutelectronics.com/Articles/How-to-add-a-class-or-id-attribute-to-a-Django-form-field.php
class NameForm(forms.Form):
    company = forms.CharField(label='Company name', initial = 'Aritari',  max_length=100,
               widget= forms.TextInput(attrs={'class':'form-control'})) ## Custom widgets with Bootstrap class properties.
 
    name = forms.CharField(label='Server name',  initial = 'Office Rapid server',max_length=100,
               widget= forms.TextInput(attrs={'class':'form-control'}))

    emaillist = forms.EmailField(label='email@address', initial = 'colin.penfound@aritari.com',
               help_text='A valid email address, please.',
               widget= forms.EmailInput(attrs={'class':'form-control'}))

    ipaddress = forms.CharField(label='IP Adress', initial = '88.150.165.135', max_length=200,
               widget= forms.TextInput(attrs={'class':'form-control'}))

    community = forms.CharField(label='SNMP Community',  initial = 'Rapidv1b3',max_length=100,
               widget= forms.TextInput(attrs={'class':'form-control'}))

    ping_test = forms.BooleanField(label='Ping Test', initial = True,required=False)
    license_check = forms.BooleanField(label='License Check', initial = True,required=False)
    SNMP_tests = forms.BooleanField(label='SNMP Tests', initial = True,required=False,
               widget= forms.CheckboxInput(attrs={ 'onclick': "showparameterform()", } ) )


## Dynamicly created form ##
## https://jacobian.org/2010/feb/28/dynamic-form-generation/
## Need to do this to dynamically define the 'name' of the inpout fields
class Parameter_dynamic (forms.Form):
    def __init__(self, *args, **kwargs):
        ## pull out the parameter names from the kwargs list
        param = kwargs.pop('param')
        mib = kwargs.pop('mib')

        ## Now initialise the main form class
        # super(Parameter_dynamic,self).__init__(*args, **kwargs)
        super().__init__(*args, **kwargs)
        self.fields[f'{param}_threshold'] = forms.IntegerField(label = 'Threshold Value', initial = 50)
        self.fields[f'{param}_enable'] = forms.BooleanField(label='Enable', initial = True, required = False)
        self.fields[f'{param}_email']  = forms.BooleanField(label='Email', initial = True,   required = False)
        # self.fields[f'{param}_mib']  = forms.CharField(label='', initial = mib, required = False,
        #                                                 widget = forms.HiddenInput() )














### Not used ###

class Quality (forms.Form):
        test = forms.CharField(label='Link Quality',  initial = 'Quality',max_length=100)
        parameter = forms.CharField(label='SNMP parameter',  initial = 'vibeRemoteQuality',max_length=100)
        email = forms.BooleanField(label='Email', initial = True)


## https://docs.djangoproject.com/en/3.1/ref/forms/widgets/
class CommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'special'})
        self.fields['comment'].widget.attrs.update(size='40')

monitor_project/monitor_app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Server, Company, ServerLink 
# Create your views here.
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.urls import reverse
import shelve
from monitor_packages.functions import *

from .forms import NameForm
from .forms import *

# https://www.edureka.co/community/73109/how-do-i-call-a-django-function-on-button-click

## https://docs.djangoproject.com/en/3.1/topics/forms/


form_parameters = [
    {'name':'TunnelStatus', 'mib': 'vibeTunnelStatus', 'threshold':False},
    {'name':'LinkQuality', 'mib': 'vibeRemoteQuality', 'threshold':True},
    {'name':'RXJitter', 'mib': 'vibeRXJitterAverage', 'threshold':True},
    {'name':'TXJitter', 'mib': 'vibeTXJitterAverage', 'threshold':True},
    {'name':'LatePackets', 'mib': 'vibeLate', 'threshold':False},
    {'name':'TunnelType', 'mib': 'vibeTunnelType', 'threshold':False},
    {'name':'Multilink', 'mib': 'vibeMultilink', 'threshold':False},


]



def check_forms_are_valid(form_list):

  for Paramform in form_list:
    if not Paramform.is_valid():
      print (f"{Paramform.name} is not valid.")
      return False

  return True


def parameter_form(name, mib, use_threshold = False, postdata = None):

    form = Parameter_dynamic(data = postdata ,  param = name, mib = mib)
    form.name = name
    form.mib_parameter = mib
    form.use_threshold = use_threshold
    if not use_threshold:
      form.fields[f'{name}_threshold'].disabled = True
    return form

@login_required
def server_form(request, form_data = None ,  report = None):

    if 'form_response' in request.path:

      print (f"request.path is {request.path}")
      print (f"form_data = {form_data}")

      print("################ request attributes ####################################")
      for attr in dir(request) :
        if not '_' in attr:
           print (f"request.{attr}  {getattr(request,attr)}")

        print ("Thanks very much")
        return render(request, 'serverapp/form_reply.html', {'name': form_data , 'report' : report})
  
    if request.method == 'POST':

        # if this is a POST request we need to process the form data
        print ("########################### request.POST.items ##########################")
        for key, val in request.POST.items():
               print (f"request.POST[{key}] = {val}")
          
        print ("POST request.POST.items")


        # create a form instance and populate it with data from the request:
        form = NameForm(data = request.POST)
        paramform_list = [ parameter_form(param['name'], param['mib'], param['threshold'],request.POST)  for param in form_parameters ]

        # check whether it's valid:
        if form.is_valid() and check_forms_are_valid(paramform_list):
        #if form.is_valid():
            print ("Form is valid")

            # if this is a POST request we need to process the form data
            print ("########################### request.POST.items valid ##########################")
            for key, val in request.POST.items():
                   print (f"request.POST[{key}] = {val}")
              
#            print ("POST request.POST.items")


            print ("   Cleaned data : ")
            for key,data in form.cleaned_data.items():
              print (f"    {key} : {data}")

            print ("--------")
            print ("   Cleaned data for paramform_list : ")
            parameterdict = {}
            for paramform in paramform_list:

                  if paramform.cleaned_data.get(paramform.name + '_enable') :
                    print (f'{paramform.name} is enabled')
                    parameterdict[paramform.name] = {key.split('_')[1]:item for key,item in paramform.cleaned_data.items()}
                    parameterdict[paramform.name]['name'] = paramform.name
                    parameterdict[paramform.name]['mib_parameter'] = paramform.mib_parameter

            form.cleaned_data['parameterlist'] = parameterdict
            print (f"form.cleaned_data is now {form.cleaned_data}")
            server = form.cleaned_data['name']
            company = form.cleaned_data['company']
            print (f"ip address : {form.cleaned_data['ipaddress']}")
            # if Company.objects.filter(name = company):
            if   Company.objects.filter(name = company):
                if Company.objects.get(name = company).server_set.filter(name  = server):
                   error =  (f" {server} already exists for {company}" )
                   print (error)
                   return render(request, 'serverapp/server_form.html', {'form': form, 'form_list' : paramform_list ,'error': error})
            
            report = add_server_to_db (form.cleaned_data)
            print (report)



            print ("--------------Redirecting ------")
            ## return HttpResponseRedirect('/thanks/')



            ### HttpResponseRedirect is used when redirecting directly to a new url, instead of rendering webpage
            ### 
            ### https://docs.djangoproject.com/en/3.1/intro/tutorial04/#write-a-minimal-form
            ### the url created will be something like :-
            ### http://127.0.0.1:8000/form_response/Aritari/Set%20up%20links%20for%20Office%20Rapid%20server2
            ### In urls.py this matches the url sting "path('form_response/<str:form_data>/<str:report>', views.server_form, name='server_form'),"
            ### and so will load the view server_form.
            ### notice there is another url for getname " path('form_newserver/', views.server_form, name='server_form'), "
            ### but the string format does not match so it will not be used.
            ### So reverse('serverapp:server_form', args=('teststring','anotherstring') )  will come back with :-
            ###   /form_response/teststring/anotherstring
            ### and reverse('serverapp:server_form') will return 
            ###   /form_newserver/
            return HttpResponseRedirect(reverse('serverapp:server_form', args=(form.cleaned_data['company'], report)  ) )
           
    # if request method is not POST but a GET (or any other method) we'll create a blank form
    else:

        print ("blank form")
        form = NameForm()
        paramform_list = [ parameter_form(param['name'], param['mib'], param['threshold'])  for param in form_parameters ]
        
        rev_url = reverse('serverapp:server_form', args=('teststring','anotherstring') )
        print (f"rev_url = {rev_url}")

    return render(request, 'serverapp/server_form.html', {'form': form, 'form_list' : paramform_list })



####################################################################################################



##def confirm_request_new (request, name, decision=None, action=None):
def confirm_request_new (request, name, action=None):

    show_requests(request)
    print (f"action from parameter : {action}")

    if request.method == 'POST':

      print (f'name {name}')
      print (f"Action : {request.POST['action']}")

      template = 'serverapp/confirm_action.html'
      context = {'name' : name , 'action': request.POST['action'],
                 'next': request.POST['next']}
      return render(request, template, context)

    else:

        url = request.GET['next']
        decision = request.GET['decision']

        print (f"url is {url}")

        if (decision == 'confirm'):
           
           if (action == 'delete'):
            print (f'Deleting {name}')
            server_obj = get_object_or_404(Server, name = name)
            try : 
              server_obj.delete()
              response = f'{name} Deleted'
            except : response = f'Failed to delete {name}'

           elif (action == 'update'):
             try:
                Server.objects.get(name = name).test_all_links()
                response = f'Links updated for {name}'
             except : response = f'Failed to update links for  {name}'

           else : response = f'Cant {action} for {name}'

        else : response = f'{name} {action} cancelled.'



        print ('response is', response)
        nexturl=f'{url}?response={response}'
        return HttpResponseRedirect (nexturl) 

      # return HttpResponse(f"Maybe Deleting {name}.<br>Next is {request.GET['next']}<br>Action is {action}<br>Decision is {request.GET['decision']}")


# def confirm_request (request, name, action):

#   print (f'name {name}')
#   print (f'action {action}')
#   print ("request.GET: ", request.GET)

#   # show_requests(request)

#   template = 'serverapp/confirm_action.html'
#   action2 = f'{action} {name}'
#   context = {'action': action, 'name' : name}

#   return render(request, template, context)



def delete_server (request, number, server_name):
    server_obj = get_object_or_404(Server, name=server_name)
    server_obj.delete()

    context = {'companies': Company.objects.all(), 'varnumber': number}
    template = f'serverapp/base{number}.html'
    return render(request, template,context)


def test_links (request, number, server_name):
          server_obj = get_object_or_404(Server, name=server_name)
          server_obj.test_all_links()

          # test_server_links(server_obj)
          #Server.objects.get(name = server_name).test_all_links()
 ##         return HttpResponse(f"Updating links for {server_obj.name} path is {request.path}")

          context = {'companies': Company.objects.all(),
                      'action' : f'{server_name} Updated',
                    'varnumber': number}

          template = f'serverapp/base.html'
          return render(request, template,context)
          # print (f"request.GET: {request.GET}")
          # next = request.GET.get('mybtn2')
          # print (f"## next: {next}")
          # return HttpResponseRedirect(next)

monitor_project/monitor_app/templates/serverapp/base2.html
{% load static %}  <!-- https://docs.djangoproject.com/en/3.0/ref/templates/builtins/#std:templatetag-static -->

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Server List</title>

    <!-- Bootstrap -->

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->

    <!-- Custom styles for this template -->
      <link rel="stylesheet" href="{% static 'serverapp/style.css' %}">
    <!-- <link href="navbar.css" rel="stylesheet"> -->
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous"> -->
    
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet">
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous"> -->


    <!-- <link href="https://getbootstrap.com/docs/4.0/examples/offcanvas/offcanvas.css" rel="stylesheet"> -->
    
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

        <!-- Bootstrap core CSS -->


  </head>

<body>


<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <img src="{% static 'serverapp/aritari-logo.png' %}" alt="Powered By Voipex" height="50px">

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

              {% if user.is_authenticated %}
                {% for company_name in companies %}
                    <!-- <li class="active"><a href="#">{{ company_name }} <span class="sr-only">(current)</span></a></li> -->
                    <li><a href="{% url 'serverapp:servertable' company_name %}">{{ company_name }}</a></li>
                {%endfor %}
             {% endif %}

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown 1<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>

      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search (Not working)">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'serverapp:viewname-new_entry' %}">New Entry</a></li>
        
            <ul class="nav navbar-nav navbar-right">
              {% if user.is_authenticated %}
                 <li><a href="{% url 'logout'%}?next={{request.path}}"><span class="glyphicon glyphicon-log-out"></span>  {{ user.get_username|capfirst }} Logout</a></li>   
              {% else %}
                 <li><a href="{% url 'login'%}?next={{request.path}}"><span class="glyphicon glyphicon-log-in"></span>  {{ user.get_username|capfirst }} Login</a></li>   
              {% endif %} 
            </ul>




        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>



      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="spinner-border text-secondary"></div>

{% block servertable %}
     <div class="container-fluid"> 
         <h2>Aritari Server Monitor</h2>
         <img src="{% static 'serverapp/aritari-logo.png' %}" alt="Powered By Voipex" height="100px">
     </div>
{% endblock servertable %}

  <footer class="my-5 pt-5 text-muted text-center text-small">
    <p class="mb-1">&copy; 2017-2020 Aritari</p>
    <ul class="list-inline">
      <li class="list-inline-item"><a href="#">Privacy</a></li>
      <li class="list-inline-item"><a href="#">Terms</a></li>
      <li class="list-inline-item"><a href="#">Support</a></li>
    </ul>
  </footer>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

monitor_project/monitor_app/templates/serverapp/confirm_action.html
{% extends 'serverapp/base.html' %}

{% block confirm %}


     <br>
     <br>

	 <h3>{{action|capfirst}} {{name}} ? </h3>
	<hr>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script>
	$(document).ready(function(){
	  $("#updating").hide()
	  $("#confirmbtn").click(function(){
	    $("#updating").show();
        $("#spinner").addClass("spinner-border spinner-border-sm")
	  });


	});
	</script>

	<button 
		type="submit" 
		id = 'confirmbtn'
		class="btn btn-secondary btn-lg" 
		style ="display: inline; "
		value= "confirm"
		onclick="location.href='{% url 'serverapp:confirm_request_new' name action %}?next={{next}}&decision=confirm'" 
		name='confirm'>
		<span id = 'spinner'></span>
		  Confirm
	</button>
                  <!-- onclick="location.href='{% url 'login'%}?next={{request.path}}'" -->

	<button 
		type="submit" 
		class="btn btn-secondary btn-lg" 
		style ="display: inline; "
		value= "cancel"
		onclick="location.href='{% url 'serverapp:confirm_request_new' name action %}?next={{next}}&decision=cancel'" 
		name='confirm'>
		  Cancel
	</button>

	  <!-- <button class="spinner-border"></button> -->

    <br><br>
    <p id = 'updating' > Updating {{name}} Please wait. </p>
{% endblock confirm %}

monitor_project/monitor_app/templates/serverapp/form_reply.html
{% extends 'serverapp/base.html' %}

{% block formreply %}


     <br>
     <br>
	<h3> Thank you. </h3>
		<p> 
				{% for key, val in request.POST.items %}
			       {{key}} : {{val}} <br>
			     {%  endfor %}
		   <!-- Created entry for  {{name}}<br> -->
		   Thank you {{ user.get_username|capfirst }}<br>
		   {{report}}
	    </p>
	<hr>

	<button 
		type="submit" 
		class="btn btn-light btn-lg" 
		style ="display: inline; "
		value= "{{ request.path }}"
		onclick="location.href='{% url 'serverapp:base' %}'" 
		name='mybtn2'>
		  Back
	</button>


{% endblock formreply %}

monitor_project/monitor_app/templates/serverapp/list_servers.html
{% block server_list %}

     <div class="col-md-2 ">
        <ul>
         <div style = "margin-left:-120px"  class="panel panel-default">
           <div class="panel-heading">{{ company_name }} servers    
</div>
              <div class="panel-body">
                {% if  {{ servers|length }} %}

          				{% for get_server in company_obj.server_set.all %}
              		      {% if get_server.name == server_name %}
                              <li  style = "margin-left:-10px" class="glyphicon glyphicon-chevron-right"><a style = "color:black" href="{% url 'serverapp:links' company_name get_server.name %}">{{ get_server.name }}</a></li>
                        {% else %}
                              <li><a style = "color:grey" href="{% url 'serverapp:links' company_name get_server.name %}">{{ get_server.name }}</a></li>
                        {% endif %}

                	{% endfor %}

                {% else  %}
                    <p>No Servers listed<p>.
                {% endif %}



              </div class="panel-body">
        </ul>
     </div class="col-md-3">

 {% endblock server_list %}

monitor_project/monitor_app/templates/serverapp/servertable.html
{% extends 'serverapp/base.html' %}

{% block servertable %}
{% load static %}

  <div class="col-md-5 order-md-1">

         <!-- <h3>{{ request.GET.response }}</h3> -->

        {% for key, value in request.GET.items %}
           <h3>{{ value }}</h3>
        {% endfor %}

       <script>
      $(document).ready(function(){
        $('[data-toggle="tooltip"]').tooltip();   
      });
      </script>


  
         {% if  servers %} 

            {% for server in servers %}
         
          <a id='{{ server.name|cut:" " }}'> <!-- marker for dropdown to jump to -->
           <form action="{% url 'serverapp:confirm_request_new' server.name %}" method="POST">

           {% csrf_token %}

            <input type="hidden" name="next" value="{{ request.path }}">
         
              <hr><br>
               <h3 data-toggle="tooltip" title="{{ server.ip_list }}" style ="display: inline"> {{ server.name }}</h3>

               <!-- <button  style ="display: inline; position: absolute; right: 0" type="button" class="btn btn-light">Update</button> -->

                <button 
                  type="submit" 
                  class="btn btn-light btn-md" 
                  style ="display: inline; position: relative; right: 0"
                  value= "update"
                  name='action'>
                    Update
                </button>

                <button 
                  type="submit" 
                  class="btn btn-light btn-md" 
                  style ="display: inline; position: relative;right:0"
                  value= "delete"
                  name='action'>
                    Delete
                </button>


              
              <table id = 'servertable' class="table table-hover">

                <thead>
                  <tr>
                    <th>No.</th>
                    <th>Link  Name</th>
                    <th>Status</th>
                  </tr>
                </thead>

                <tbody>
                  {% for link in server.serverlink_set.all %}
                    <tr style=" color: {{ link.colour }};">
                      <th scope="row">{{ link.oid }}</a></th>
                      <td><a id = 'linkname' href="{% url 'serverapp:linkparameters' company_obj.name server.name link.name %}" style="color: {{ link.colour }}">{{  link.name }}</a></td>
                      <td>{{ link.status }}</td>
                    </tr>
                  {% endfor %}
                </tbody>

              </table>
              <br><br>
          </form>

            {% endfor %}
         {% else  %}
                <h3>No servers for {{ company_name }}</h3><br>
               <img src="{% static 'serverapp/aritari-logo.png' %}" alt="Powered By Voipex" height="100px"><br><br>

         {% endif %}
         </a> <!-- marker for dropdown to jump to -->


   </div class="col-md-5 order-md-1">

{% block parameter_table %}

{% endblock parameter_table %}

{% endblock servertable %}